version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    platform: linux/amd64
    volumes:
      - data-volume:/var/lib/mysql
  web:
    image: pbm_cloud
    container_name: pbm_cloud
    build: .
    ports:
      - "5000:5000"
    volumes:
      - '.:/app:delegated'
      - bundle:/vendor/bundle
    environment:
      - BUNDLE_PATH:/vendor/bundle
    command: /bin/sh -c "rm -f tmp/pids/server.pid; bin/rails s -p 5000 -b 0.0.0.0"
volumes:
  bundle:
    driver: local
  data-volume:
