version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6378:6379"
    volumes:
      - "./data/redis:/data"
  db:
    image: mysql:5.7
    ports:
      - "9306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    platform: linux/amd64
    volumes:
      - data-volume:/var/lib/mysql
  web:
    image: pbm_cloud
    container_name: pbm_cloud
    build:
      target: dev
      context: .
    ports:
      - "5000:5000"
    volumes:
      - '.:/app'
      - bundle:/vendor/bundle
    environment:
      BUNDLE_PATH: /vendor/bundle
      REDIS_URL: redis://redis:6379/0
    command: bin/dev
volumes:
  bundle:
    driver: local
  data-volume:
