version: '3'
services:
  web:
    image: pbm_cloud
    container_name: pbm_cloud
    build: .
    ports:
      - "3000:3000"
    volumes:
      - '.:/app:delegated'
      - bundle:/vendor/bundle
    environment:
      - BUNDLE_PATH:/vendor/bundle
volumes:
  bundle:
    driver: local
