version: '3'
services:
  web:
    image: pbm_cloud
    container_name: pbm_cloud
    build: .
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - './:/app:delegated'
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
volumes:
  bundle_path:
