default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'root') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: pbm_cloud_development
  pool: 100

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_DB', 'pbm_cloud_test') %>

# production:
#   <<: *default
#   database: pbm_cloud_production
