default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'root') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: pbm_cloud_development

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_DB', 'pbm_cloud_test') %>

# 本番ではDATABASE_URL経由で取得するのでprecompileを通すために適当に埋める
production:
  adapter: mysql2
  database: pbm_cloud_production
  url: <%= ENV['DATABASE_URL2'] %>
