name: Secrets Scan

on: [push]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITLEAKS_CONFIG: .gitleaks.toml
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@v1.6.0
